/**
 * Cloudflare R2 Object Storage utility
 * Uses the S3-compatible API via @aws-sdk/client-s3
 *
 * Environment variables required:
 *   R2_ENDPOINT          – S3-compatible endpoint for the R2 bucket
 *   R2_ACCESS_KEY_ID     – R2 API token access key
 *   R2_SECRET_ACCESS_KEY – R2 API token secret key
 *   R2_BUCKET_NAME       – Name of the R2 bucket
 *   R2_PUBLIC_URL        – Public URL prefix for the bucket (r2.dev or custom domain)
 */

const { S3Client, PutObjectCommand, DeleteObjectCommand } = require("@aws-sdk/client-s3");
const crypto = require("crypto");
const path = require("path");

const s3 = new S3Client({
  region: "auto",
  endpoint: process.env.R2_ENDPOINT,
  credentials: {
    accessKeyId: process.env.R2_ACCESS_KEY_ID,
    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY,
  },
});

/**
 * Upload an audio file buffer to Cloudflare R2.
 *
 * @param {object}  file          – multer file object (memoryStorage), must have .buffer, .mimetype, .originalname
 * @param {number|string} setId   – material set ID, used to namespace the key
 * @returns {Promise<{key: string, publicUrl: string, fileName: string}>}
 */
const uploadAudioToR2 = async (file, setId) => {
  const ext = path.extname(file.originalname).toLowerCase() || ".mp3";
  const safeName = `${Date.now()}_${crypto.randomUUID()}${ext}`;
  const key = `listening/material-set-${setId}/${safeName}`;

  await s3.send(
    new PutObjectCommand({
      Bucket: process.env.R2_BUCKET_NAME,
      Key: key,
      Body: file.buffer,
      ContentType: file.mimetype,
    })
  );

  const publicUrl = `${process.env.R2_PUBLIC_URL.replace(/\/+$/, "")}/${key}`;

  return {
    key,
    publicUrl,
    fileName: file.originalname,
  };
};

/**
 * Delete an object from R2 by its key.
 * Swallows errors so callers can continue even if deletion fails.
 *
 * @param {string} key – the R2 object key (e.g. "listening/material-set-12/abc.mp3")
 */
const deleteFromR2 = async (key) => {
  try {
    await s3.send(
      new DeleteObjectCommand({
        Bucket: process.env.R2_BUCKET_NAME,
        Key: key,
      })
    );
    console.log(`R2: deleted ${key}`);
  } catch (err) {
    console.warn(`R2: failed to delete ${key} –`, err.message);
  }
};

/**
 * Check whether a stored audio_file_path looks like an R2 object key
 * (as opposed to a legacy local filesystem path).
 *
 * R2 keys generated by this module always start with "listening/".
 * Local paths typically start with "/" or contain backslashes.
 *
 * @param {string} filePath
 * @returns {boolean}
 */
const isR2Key = (filePath) => {
  if (!filePath || typeof filePath !== "string") return false;
  return filePath.startsWith("listening/");
};

module.exports = {
  uploadAudioToR2,
  deleteFromR2,
  isR2Key,
};
